import { AvailableCities, AvailableMainCities } from '@services/filters/city-filter/city-list'
import { capitalizeFirstLetter } from '@services/helpers/capitalize'

export const label = (city: AvailableMainCities | AvailableCities): string => {
  switch (city) {
    case 'paris': return 'Paris'
    case 'lyon': return 'Lyon'
    case 'lille': return 'Lille'
    case 'plaineCommune': return 'Plaine Commune'
    case 'estEnsemble': return 'Est Ensemble'
    case 'montpellier': return 'Montpellier'
    case 'bordeaux': return 'Bordeaux'
    case 'aubervilliers': return 'Aubervilliers'
    case 'epinay-sur-seine': return 'Épinay-sur-Seine'
    case 'ile-saint-denis': return 'L\'Île-Saint-Denis'
    case 'courneuve': return 'La Courneuve'
    case 'pierrefitte': return 'Pierrefitte-sur-Seine'
    case 'saint-denis': return 'Saint-Denis'
    case 'saint-ouen': return 'Saint-Ouen-sur-Seine'
    case 'stains': return 'Stains'
    case 'villetaneuse': return 'Villetaneuse'
    case 'villeurbanne': return 'Villeurbanne'
    case 'bagnolet': return 'Bagnolet'
    case 'bobigny': return 'Bobigny'
    case 'bondy': return 'Bondy'
    case 'le pré-saint-gervais': return 'Le Pré Saint-Gervais'
    case 'les lilas': return 'Les Lilas'
    case 'montreuil': return 'Montreuil'
    case 'noisy-le-sec': return 'Noisy-le-Sec'
    case 'pantin': return 'Pantin'
    case 'romainville': return 'Romainville'
    case 'la rochelle': return 'La Rochelle'
    case 'marseille': return 'Marseille'
    case 'nice': return 'Nice'
    case 'nantes': return 'Nantes'
    case 'strasbourg': return 'Strasbourg'
    case 'rennes': return 'Rennes'
    case 'toulon': return 'Toulon'
    case 'toulouse': return 'Toulouse'
    case 'aix-en-provence': return 'Aix-en-Provence'
    case 'annecy': return 'Annecy'
    case 'paysBasque': return 'Pays Basque'
    case 'ahetze': return 'Ahetze'
    case 'anglet': return 'Anglet'
    case 'arbonne': return 'Arbonne'
    case 'arcangues': return 'Arcangues'
    case 'ascain': return 'Ascain'
    case 'bassussarry': return 'Bassussarry'
    case 'bayonne': return 'Bayonne'
    case 'biarritz': return 'Biarritz'
    case 'bidart': return 'Bidart'
    case 'biriatou': return 'Biriatou'
    case 'boucau': return 'Boucau'
    case 'ciboure': return 'Ciboure'
    case 'guéthary': return 'Guéthary'
    case 'hendaye': return 'Hendaye'
    case 'jatxou': return 'Jatxou'
    case 'lahonce': return 'Lahonce'
    case 'larressore': return 'Larressore'
    case 'mouguerre': return 'Mouguerre'
    case 'saint-jean-de-luz': return 'Saint-Jean-de-Luz'
    case 'saint-pierre-d\'irube': return 'Saint-Pierre-d\'Irube'
    case 'urcuit': return 'Urcuit'
    case 'urrugne': return 'Urrugne'
    case 'ustaritz': return 'Ustaritz'
    case 'villefranque': return 'Villefranque'

    case 'bresson': return 'Bresson'
    case 'claix': return 'Claix'
    case 'domène': return 'Domène'
    case 'échirolles': return 'Échirolles'
    case 'eybens': return 'Eybens'
    case 'fontaine': return 'Fontaine'
    case 'fontanil-cornillon': return 'Fontanil-Cornillon'
    case 'gières': return 'Gières'
    case 'grenoble': return 'Grenoble'
    case 'la tronche': return 'La Tronche'
    case 'le pont-de-claix': return 'Le Pont-de-Claix'
    case 'meylan': return 'Meylan'
    case 'murianette': return 'Murianette'
    case 'poisat': return 'Poisat'
    case 'saint-égrève': return 'Saint-Égrève'
    case 'saint-martin-d\'hères': return 'Saint-Martin-d\'Hères'
    case 'sassenage': return 'Sassenage'
    case 'seyssinet-pariset': return 'Seyssinet-Pariset'
    case 'seyssins': return 'Seyssins'
    case 'varces-allières-et-risset': return 'Varces-Allières-et-Risset'
    case 'venon': return 'Venon'

    default: return capitalizeFirstLetter(city)
  }
}