# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    env:
      MONGODB_URI_EMPRISE_BATIE: ${{ secrets.MONGODB_URI_EMPRISE_BATIE }}
      MONGODB_URI_ENCADREMENT_ADDRESS1: ${{ secrets.MONGODB_URI_ENCADREMENT_ADDRESS1 }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
        mongodb-version: ['4.0', '4.2', '4.4']
    steps:
      - name: Copy repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test
        env:
          CI: true

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{js,ts}
